name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-mac:
    runs-on: macos-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Download FFmpeg for macOS
      run: |
        # Download FFmpeg binaries that will be packaged with the app
        echo "Downloading FFmpeg for macOS..."
        
        # Download FFmpeg from Evermeet.cx
        echo "Downloading FFmpeg for macOS..."
        curl -L -f "https://evermeet.cx/ffmpeg/get/ffmpeg" -o ffmpeg.zip
        
        echo "Extracting FFmpeg to temp directory..."
        unzip -q ffmpeg.zip -d ffmpeg_temp/
        
        # Download ffprobe from Evermeet.cx
        echo "Downloading ffprobe for macOS..."
        curl -L -f "https://evermeet.cx/ffmpeg/get/ffprobe" -o ffprobe.zip
        
        echo "Extracting ffprobe to temp directory..."
        unzip -q ffprobe.zip -d ffprobe_temp/
        
        echo "Checking contents of temp directories..."
        echo "ffmpeg_temp contents:"
        ls -la ffmpeg_temp/
        echo "ffprobe_temp contents:"
        ls -la ffprobe_temp/
        
        echo "Copying files to root directory..."
        cp ffmpeg_temp/ffmpeg ./ffmpeg
        cp ffprobe_temp/ffmpeg ./ffprobe
        
        echo "Cleaning up temp directories..."
        rm -rf ffmpeg_temp/ ffprobe_temp/
        
        echo "Checking extracted files..."
        ls -la ffmpeg*
        
        # Make executable
        chmod +x ffmpeg ffprobe
        
        # Verify
        echo "Verifying FFmpeg installation..."
        ./ffmpeg -version
        ./ffprobe -version
        
        echo "FFmpeg download and setup completed successfully!"
        
    - name: Build macOS app
      run: |
        echo "Current directory: $(pwd)"
        echo "FFmpeg installation verified:"
        which ffmpeg
        which ffprobe
        ffmpeg -version | head -1
        echo "Building macOS app..."
        npm run build-mac
      env:
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
        
    - name: Upload macOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MediaSpooferPro-macOS
        path: dist/
        
  build-win:
    runs-on: windows-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Download FFmpeg for Windows
      run: |
        # Download FFmpeg for Windows with multiple fallback sources
        Write-Host "Downloading FFmpeg for Windows..."
        
        $sources = @(
          "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip",
          "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip",
          "https://github.com/ffmpeg/ffmpeg/releases/download/n6.1/ffmpeg-6.1-full_build.zip"
        )
        
        $ffmpegZip = "ffmpeg-win.zip"
        $downloadSuccess = $false
        
        foreach ($source in $sources) {
          try {
            Write-Host "Trying source: $source"
            Invoke-WebRequest -Uri $source -OutFile $ffmpegZip -UseBasicParsing
            
            # Verify file size
            $fileInfo = Get-Item $ffmpegZip
            if ($fileInfo.Length -gt 1000000) {  # More than 1MB
              Write-Host "Successfully downloaded from: $source"
              $downloadSuccess = $true
              break
            } else {
              Write-Host "File too small, trying next source..."
              Remove-Item $ffmpegZip -Force
            }
          } catch {
            Write-Host "Failed to download from: $source"
            Write-Host "Error: $($_.Exception.Message)"
            if (Test-Path $ffmpegZip) {
              Remove-Item $ffmpegZip -Force
            }
          }
        }
        
        if (-not $downloadSuccess) {
          Write-Host "ERROR: All download sources failed!"
          exit 1
        }
        
        Write-Host "Extracting FFmpeg..."
        Expand-Archive -Path $ffmpegZip -DestinationPath "ffmpeg-temp" -Force
        
        Write-Host "Searching for FFmpeg binaries..."
        $ffmpegExe = Get-ChildItem -Path "ffmpeg-temp" -Recurse -Name "ffmpeg.exe" | Select-Object -First 1
        $ffprobeExe = Get-ChildItem -Path "ffmpeg-temp" -Recurse -Name "ffprobe.exe" | Select-Object -First 1
        
        if (-not $ffmpegExe -or -not $ffprobeExe) {
          Write-Host "ERROR: Could not find FFmpeg binaries in extracted files"
          Write-Host "Contents of ffmpeg-temp:"
          Get-ChildItem -Path "ffmpeg-temp" -Recurse | Select-Object FullName
          exit 1
        }
        
        Write-Host "Copying FFmpeg binaries to root directory..."
        Copy-Item "ffmpeg-temp\$ffmpegExe" "ffmpeg.exe"
        Copy-Item "ffmpeg-temp\$ffprobeExe" "ffprobe.exe"
        
        Write-Host "Verifying FFmpeg installation..."
        .\ffmpeg.exe -version
        .\ffprobe.exe -version
        
        Write-Host "Cleaning up..."
        Remove-Item -Recurse -Force "ffmpeg-temp"
        Remove-Item $ffmpegZip -Force
        
        Write-Host "FFmpeg setup completed successfully!"
        
    - name: Build Windows app
      run: |
        echo "Current directory: $(pwd)"
        echo "FFmpeg files before build:"
        dir ffmpeg*
        echo "Building Windows app..."
        npm run build-win
      env:
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
        
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MediaSpooferPro-Windows
        path: dist/
        
  release:
    needs: [build-mac, build-win]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create release assets
      run: |
        mkdir -p release-assets
        mv MediaSpooferPro-macOS/* release-assets/ || true
        mv MediaSpooferPro-Windows/* release-assets/ || true
        echo "Release assets created:"
        ls -la release-assets/
        
        # Find and rename the actual files for upload
        # Look for universal DMG first, then fallback to any DMG
        universal_dmg=$(find release-assets -name "*.dmg" -not -name "*arm64*" -not -name "*x64*" | head -1)
        if [ -n "$universal_dmg" ]; then
          echo "Found universal macOS DMG: $universal_dmg"
          cp "$universal_dmg" "MediaSpooferPro-${{ github.event.release.tag_name }}-macOS.dmg"
        else
          # Fallback to any DMG file
          for file in release-assets/*.dmg; do
            if [ -f "$file" ]; then
              echo "Found macOS DMG: $file"
              cp "$file" "MediaSpooferPro-${{ github.event.release.tag_name }}-macOS.dmg"
              break
            fi
          done
        fi
        
        for file in release-assets/*.exe; do
          if [ -f "$file" ]; then
            echo "Found Windows EXE: $file"
            cp "$file" "MediaSpooferPro-${{ github.event.release.tag_name }}-Windows.exe"
          fi
        done
        
        echo "Files ready for upload:"
        ls -la MediaSpooferPro-*
        
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          MediaSpooferPro-${{ github.event.release.tag_name }}-macOS.dmg
          MediaSpooferPro-${{ github.event.release.tag_name }}-Windows.exe
        tag_name: ${{ github.event.release.tag_name }}
        name: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
        draft: false
        prerelease: false 